// <auto-generated />
using System;
using IVYTS_Final_Proje.Module.BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IVYTS_Final_Proje.Module.Migrations
{
    [DbContext(typeof(IVYTS_Final_ProjeEFCoreDbContext))]
    partial class IVYTS_Final_ProjeEFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", true)
                .HasAnnotation("Proxies:CheckEquality", true)
                .HasAnnotation("Proxies:LazyLoading", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.OneHotEncodedCarData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Car_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Fuel_Type_Diesel")
                        .HasColumnType("bit");

                    b.Property<bool>("Fuel_Type_Petrol")
                        .HasColumnType("bit");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<bool>("Seller_Type_Individual")
                        .HasColumnType("bit");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.Property<bool>("Transmission_Manual")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("OneHotEncodedCarData");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.OriginalCarData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Car_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuel_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<string>("Seller_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("OriginalCarData");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.Random_Data", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Fuel_Type_Diesel")
                        .HasColumnType("bit");

                    b.Property<bool>("Fuel_Type_Petrol")
                        .HasColumnType("bit");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<bool>("Seller_Type_Individual")
                        .HasColumnType("bit");

                    b.Property<bool>("Transmission_Manual")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Random_Data");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.Random_Data_Prediction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Random_Data_Prediction");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.Random_Data_Scaled", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Fuel_Type_Diesel")
                        .HasColumnType("real");

                    b.Property<float>("Fuel_Type_Petrol")
                        .HasColumnType("real");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<float>("Owner")
                        .HasColumnType("real");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<float>("Seller_Type_Individual")
                        .HasColumnType("real");

                    b.Property<float>("Transmission_Manual")
                        .HasColumnType("real");

                    b.Property<float>("Year")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Random_Data_Scaled");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.X_Test", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Fuel_Type_Diesel")
                        .HasColumnType("bit");

                    b.Property<bool>("Fuel_Type_Petrol")
                        .HasColumnType("bit");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<bool>("Seller_Type_Individual")
                        .HasColumnType("bit");

                    b.Property<bool>("Transmission_Manual")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("X_Test");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.X_Test_Scaled", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Fuel_Type_Diesel")
                        .HasColumnType("real");

                    b.Property<float>("Fuel_Type_Petrol")
                        .HasColumnType("real");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<float>("Owner")
                        .HasColumnType("real");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<float>("Seller_Type_Individual")
                        .HasColumnType("real");

                    b.Property<float>("Transmission_Manual")
                        .HasColumnType("real");

                    b.Property<float>("Year")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("X_Test_Scaled");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.X_Train", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Fuel_Type_Diesel")
                        .HasColumnType("bit");

                    b.Property<bool>("Fuel_Type_Petrol")
                        .HasColumnType("bit");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<bool>("Seller_Type_Individual")
                        .HasColumnType("bit");

                    b.Property<bool>("Transmission_Manual")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("X_Train");
                });

            modelBuilder.Entity("IVYTS_Final_Proje.Module.BusinessObjects.X_Train_Scaled", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Fuel_Type_Diesel")
                        .HasColumnType("real");

                    b.Property<float>("Fuel_Type_Petrol")
                        .HasColumnType("real");

                    b.Property<float>("Kms_Driven")
                        .HasColumnType("real");

                    b.Property<float>("Owner")
                        .HasColumnType("real");

                    b.Property<float>("Present_Price")
                        .HasColumnType("real");

                    b.Property<float>("Seller_Type_Individual")
                        .HasColumnType("real");

                    b.Property<float>("Transmission_Manual")
                        .HasColumnType("real");

                    b.Property<float>("Year")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("X_Train_Scaled");
                });

            modelBuilder.Entity("VYTSFinalProje.Module.BusinessObjects.Test_Prediction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Test_Prediction");
                });

            modelBuilder.Entity("VYTSFinalProje.Module.BusinessObjects.Trained_Prediction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Trained_Prediction");
                });

            modelBuilder.Entity("VYTSFinalProje.Module.BusinessObjects.Y_Test", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Y_Test");
                });

            modelBuilder.Entity("VYTSFinalProje.Module.BusinessObjects.Y_Train", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Selling_Price")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Y_Train");
                });
#pragma warning restore 612, 618
        }
    }
}
